### ISSUE TITLE
Response different than expected

### ISSUE THREAD

**Issue by peterjaap** [michelecurletta/laravel-cloudflare-purge#1]
When running this, I get;

```
➜  project git:(master) ✗ php artisan cloudflare-cache:purge


  [ErrorException]
  Undefined offset: 0
```

When I `print_r` the json response by putting `print_r($response->json());exit;` on line 81 of CloudflarePurgeCommand, I get;

```
Array
(
    [result] => Array
        (
        )

    [result_info] => Array
        (
            [page] => 1
            [per_page] => 20
            [total_pages] => 0
            [count] => 0
            [total_count] => 0
        )

    [success] => 1
    [errors] => Array
        (
        )

    [messages] => Array
        (
        )

)
```

But your PHP says;

```php
if(($zoneId = $response->json()['result'][0]['id']))
```

So the response I'm getting it different than yours, although the purge is succesful (see 'success').

**Comment by michelecurletta** [comment]
hi @peterjaap ,
could you please give me more details about your configs?
What version of PHP and Guzzle are you using?

**Comment by peterjaap** [comment]
PHP 7.0.11

```
guzzlehttp/guzzle                        5.3.1   Guzzle is a PHP HTTP client library and framework for building RESTful web service clients
guzzlehttp/psr7                          1.3.1   PSR-7 message implementation
guzzlehttp/ringphp                       1.1.0   Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                       3.0.0   Provides a simple abstraction over streams of data
```

**Comment by michelecurletta** [comment]
Do you have setted the right config parameters into .env file?
```
CLOUDFLARE_EMAIL=mail@domain.ext
CLOUDFLARE_API_KEY=0c23444e625aqe5cc324234wqweqwwewqe
CLOUDFLARE_DOMAIN_NAME=domain.ext
```

or directly into the config/laravel-cloudflare-purge.php file?

```
 /*
    |--------------------------------------------------------------------------
    | Cloudflare email
    |--------------------------------------------------------------------------
    |   The email used with Cloudflare account
    |   
    */
    'email' => env('CLOUDFLARE_EMAIL', ''),

    /*
    |--------------------------------------------------------------------------
    | API Key
    |--------------------------------------------------------------------------
    |   The API Key used to perform requests to Cloudflare's API.
    |   You can find it into your account's settings page.
    |   
    |
    */

    'api_key' => env('CLOUDFLARE_API_KEY', ''),

    /*
    |--------------------------------------------------------------------------
    | Domain name
    |--------------------------------------------------------------------------
    |   The domain whose the cache is related to.
    |   
    |
    */

    'zone_name' => env('CLOUDFLARE_DOMAIN_NAME', '')
```

**Comment by peterjaap** [comment]
Yes, I configured in in the config file. The purging works fine, just the structure of the response is different than your code expects.

**Comment by michelecurletta** [comment]
If you've putted the print_r on line 81, you're printing the response of the "get zones" request, not the purge request (the "purgeZone" method does it).
The "success" string is informing you that that specific http request has finished successfully.

Your printed response seems to have an empty "result" array
` [result] => Array
        (
        )`
So, there are no zones available for the configured account (and you cannot purge anything if no zones are available).
You should review you config parameters (associated to you cloudflare account).
Make sure that you've enabled the cache on cloudflare's control panel for at least one DNS record , under "DNS" tab.
After that, if your configs are valid and will work properly, running the command from the terminal, you'll see an output like this:
`mike@macbookpro:~/test-env$ php artisan cloudflare-cache:purge

Zone id: 694d43212924e339f3c7a13489e3a414
So far, so good. CDN purged!`

**Comment by peterjaap** [comment]
Right, my zone wasn't competely done configuring yet, but the purge function in Cloudflare itself did work so I figured this should work as well, but alas. Thanks for your explanation!

**Comment by michelecurletta** [comment]
@peterjaap you're welcome
