### ISSUE TITLE
Conflicts guzzle version

### ISSUE THREAD

**Issue by jorgeneira** [michelecurletta/laravel-cloudflare-purge#2]
Hi,

Is there any reason why you're not using the latest guzzle version? I can't use this package as it is because I'm using guzzle ^6.1 and it requires 5.3

Thank you

**Comment by michelecurletta** [comment]
Hi @jorgeneira, there's no reason.
I'd accept a PR that upgrades used Guzzle version.

**Comment by jorgeneira** [comment]
Done #3  

Thank you

**Comment by michelecurletta** [comment]
Did you have performed any tests to check package's compatibility with the new version?

**Comment by jorgeneira** [comment]
I'm sorry, I misunderstood you. I added a commit to the PR changing the old guzzle api to guzzle 6. I'm already using it, it works fine.

**Comment by michelecurletta** [comment]
See #3

**Comment by michelecurletta** [comment]
@jorgeneira new version available (1.1.0)

**Comment by jorgeneira** [comment]
@michelecurletta Thank you!
